title: Vermicompost
email: jolayfield@gmail.com
baseurl: "/vermicompost" # the subpath of your site, e.g. /blog
url: "https://jolayfield.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jolayfield   
tagline: A Worm Blog
author: Joshua Layfield 
theme: jekyll-theme-leap-day
# Build settings
#theme: minima
plugins:
  - jekyll-feed
